### ISSUE TITLE
All Icons are not supported

### ISSUE THREAD

**Issue by vipulgupta27** [venishpatidar/react-native-gradient-icon#1]
Hi, 
Your package is good but i am not able to used all icons which described in link [react-native vector icons directory list](https://oblador.github.io/react-native-vector-icons/) 

For ex -- 

```
<Icon
      size={70}
      mode='radial'
      colors={[
        { color: "gold", offset: "0.3", opacity: "0.5" },
        { color: "red", offset: "0.7", opacity: "0.5" },
      ]}
      style={{ alignSelf: 'center' }}
      name="lock-reset" 
      type="material-community" 
/>

```

Please help me so I can use the package.

**Comment by venishpatidar** [comment]
@vipulgupta27  Bug resolved, You can use it now.

**Comment by muhamadjawad** [comment]
Still many icons are not supported
