### ISSUE TITLE
Dependency Update Request

### ISSUE THREAD

**Issue by empobla** [venishpatidar/react-native-gradient-icon#3]
Would it be possible to update the `@react-native-community/masked-view` (deprecated) dependency to the newer `@react-native-masked-view/masked-view` dependency due to compatibility issues between both dependencies?

Also, it would be great if the prop `androidRenderingMode` from the newer  `@react-native-masked-view/masked-view` could be added to the `Icon` component, as there have been several rendering errors (icons do not render) on android due to not being able to use `androidRenderingMode = 'software'` (default is set to `hardware`).

Thanks!

**Comment by venishpatidar** [comment]
Updated and thanks for suggestion and patience
